global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'netmind'
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 4s
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          instance: 'netmind-host'
